import java.nio.charset.StandardCharsets;
import java.util.*;

public final class Brush {
  private Brush() {}
  public static final class Point { public final double x,y; public Point(double x,double y){this.x=x;this.y=y;} }
  public static final class DrawingPath { public final List<Point> points; public final String d; public final double fontSize; DrawingPath(List<Point> p,String d,double f){points=p;this.d=d;fontSize=f;} }
  private static final class Segment { Point a,b; double start,length; Segment(Point a,Point b,double s,double l){this.a=a;this.b=b;start=s;length=l;} }
  public static final class ArcPath { final List<Point> points; final List<Segment> segments; public final double totalLength; ArcPath(List<Point> p,List<Segment>s,double l){points=p;segments=s;totalLength=l;} }
  public static final class PathSample { public final double x,y,angle,progress; PathSample(double x,double y,double a,double p){this.x=x;this.y=y;angle=a;progress=p;} }
  public static final class Options { public double fontSize=40,letterSpacing=Double.NaN,opacity=1,strokeWidth=1.5,revealProgress=1;public String fontFamily="Arial, sans-serif",fontWeight="700",color="#ffffff",strokeColor="rgba(15,23,42,0.72)";public boolean magicGradient=false,shadow=true,repeatText=true; }
  private static boolean finite(Point p){return p!=null&&Double.isFinite(p.x)&&Double.isFinite(p.y);}private static double clamp(double v,double a,double b){return Double.isFinite(v)?Math.min(b,Math.max(a,v)):a;}private static double dist(Point a,Point b){return Math.hypot(b.x-a.x,b.y-a.y);}
  private static String fmt(double v){double n=Math.round(v*100d)/100d;if(n==0)return"0";String s=String.format(Locale.ROOT,"%.2f",n);return s.replaceFirst("\\.?0+$","");}private static String fp(Point p){return fmt(p.x)+" "+fmt(p.y);}private static Point along(Point a,Point b,double d){double l=dist(a,b);if(l==0)return a;double t=Math.min(1,d/l);return new Point(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t);}private static double turn(Point a,Point b,Point c){double ux=b.x-a.x,uy=b.y-a.y,vx=c.x-b.x,vy=c.y-b.y,ul=Math.hypot(ux,uy),vl=Math.hypot(vx,vy);return ul==0||vl==0?0:Math.toDegrees(Math.acos(clamp((ux*vx+uy*vy)/(ul*vl),-1,1)));}
  public static String buildRoundedDrawingPath(List<Point> input,double fontSize){List<Point> p=new ArrayList<>();for(Point v:input)if(finite(v))p.add(v);if(p.isEmpty())return"";if(p.size()==1)return"M "+fp(p.get(0));List<String> out=new ArrayList<>();out.add("M "+fp(p.get(0)));double radius=Math.max(12,fontSize*1.25);for(int i=1;i<p.size()-1;i++){Point a=p.get(i-1),b=p.get(i),c=p.get(i+1);double d=Math.min(radius,Math.min(dist(a,b)*.45,dist(b,c)*.45));out.add("L "+fp(along(b,a,d))+" Q "+fp(b)+" "+fp(along(b,c,d)));}out.add("L "+fp(p.get(p.size()-1)));return String.join(" ",out);}
  public static DrawingPath createDrawingPath(Point p,double fs){return finite(p)?new DrawingPath(new ArrayList<>(List.of(p)),"M "+fp(p),fs):new DrawingPath(new ArrayList<>(),"",fs);}public static DrawingPath appendDrawingPoint(DrawingPath path,Point point){if(!finite(point)||path.points.isEmpty()||dist(path.points.get(path.points.size()-1),point)<3)return path;List<Point> p=new ArrayList<>(path.points);if(p.size()==1||turn(p.get(p.size()-2),p.get(p.size()-1),point)>=18)p.add(point);else p.set(p.size()-1,point);return new DrawingPath(p,buildRoundedDrawingPath(p,path.fontSize),path.fontSize);}public static DrawingPath drawingPathFromPoints(List<Point> points,double fs){DrawingPath path=null;for(Point p:points)if(finite(p)){if(path==null)path=createDrawingPath(p,fs);else path=appendDrawingPoint(path,p);}return path!=null&&path.points.size()>=2?path:null;}
  private static double perp(Point p,Point a,Point b){double dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(l==0)return dist(p,a);double t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return dist(p,new Point(a.x+t*dx,a.y+t*dy));}private static List<Point> simplify(List<Point> p,double tolerance){if(p.size()<=2)return p;boolean[]keep=new boolean[p.size()];keep[0]=keep[p.size()-1]=true;Deque<int[]> stack=new ArrayDeque<>();stack.push(new int[]{0,p.size()-1});while(!stack.isEmpty()){int[]r=stack.pop();double best=0;int index=-1;for(int i=r[0]+1;i<r[1];i++){double d=perp(p.get(i),p.get(r[0]),p.get(r[1]));if(d>best){best=d;index=i;}}if(best>tolerance){keep[index]=true;stack.push(new int[]{r[0],index});stack.push(new int[]{index,r[1]});}}List<Point>result=new ArrayList<>();for(int i=0;i<p.size();i++)if(keep[i])result.add(p.get(i));return result;}
  public static ArcPath prepareArcLengthPath(List<Point> input,double minimum){minimum=Double.isFinite(minimum)?Math.max(0,minimum):.5;List<Point> valid=new ArrayList<>(),filtered=new ArrayList<>();for(Point p:input)if(finite(p))valid.add(p);for(Point p:valid)if(filtered.isEmpty()||dist(filtered.get(filtered.size()-1),p)>=minimum)filtered.add(p);if(!valid.isEmpty()&&!filtered.isEmpty()&&dist(filtered.get(filtered.size()-1),valid.get(valid.size()-1))>0)filtered.add(valid.get(valid.size()-1));List<Point>p=simplify(filtered,Math.max(minimum*.5,.1));List<Segment>s=new ArrayList<>();double total=0;for(int i=1;i<p.size();i++){double l=dist(p.get(i-1),p.get(i));if(l>0){s.add(new Segment(p.get(i-1),p.get(i),total,l));total+=l;}}return new ArcPath(p,s,total);}private static Point pointAt(ArcPath p,double d){if(p.segments.isEmpty())return new Point(0,0);d=clamp(d,0,p.totalLength);for(Segment s:p.segments)if(d<=s.start+s.length){double t=clamp((d-s.start)/s.length,0,1);return new Point(s.a.x+(s.b.x-s.a.x)*t,s.a.y+(s.b.y-s.a.y)*t);}return p.segments.get(p.segments.size()-1).b;}public static PathSample sampleAt(ArcPath p,double progress,double fs){progress=clamp(progress,0,1);if(p.totalLength<=0)return new PathSample(0,0,0,progress);double d=p.totalLength*progress,w=Math.max(Math.min(Math.max(fs*1.1,.75),p.totalLength*.06),.75);Point a=pointAt(p,d-w),b=pointAt(p,d+w),v=pointAt(p,d);return new PathSample(v.x,v.y,Math.atan2(b.y-a.y,b.x-a.x),progress);}
  public static String stableRepeatedText(String text,double fs){String p=text.trim();if(p.isEmpty())return"";int chars=p.codePointCount(0,p.length()),count=Math.min(256,Math.max(16,(int)Math.ceil(20000/Math.max(fs,chars*fs*.62))));return String.join("   ",Collections.nCopies(count,p));}private static String esc(Object value){return String.valueOf(value).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
  public static String renderSvg(byte[] bytes,String mime,double width,double height,List<Point>points,String text,Options options){Options o=options==null?new Options():options;if(!Set.of("image/png","image/jpeg","image/webp","image/gif","image/avif").contains(mime))throw new IllegalArgumentException("unsupported MIME");if(!(Double.isFinite(width+height)&&width>0&&height>0))throw new IllegalArgumentException("invalid dimensions");String phrase=text.trim();double fs=Double.isFinite(o.fontSize)&&o.fontSize>0?o.fontSize:40;DrawingPath path=drawingPathFromPoints(points,fs);if(phrase.isEmpty()||path==null)throw new IllegalArgumentException("text and two points required");String repeat=o.repeatText?stableRepeatedText(phrase,fs):phrase,gradient=o.magicGradient?"<linearGradient id=\"brush-gradient\" x1=\"100\" y1=\"150\" x2=\"900\" y2=\"850\" gradientUnits=\"userSpaceOnUse\"><stop offset=\"0%\" stop-color=\"#ec4899\"/><stop offset=\"20%\" stop-color=\"#f97316\"/><stop offset=\"40%\" stop-color=\"#facc15\"/><stop offset=\"60%\" stop-color=\"#10b981\"/><stop offset=\"80%\" stop-color=\"#3b82f6\"/><stop offset=\"100%\" stop-color=\"#8b5cf6\"/></linearGradient>":"",shadow=o.shadow?"<filter id=\"brush-shadow\"><feDropShadow dx=\"0\" dy=\"2\" stdDeviation=\"2\" flood-color=\"#0f172a\" flood-opacity=\"0.65\"/></filter>":"",fill=o.magicGradient?"url(#brush-gradient)":esc(o.color),filter=o.shadow?" filter=\"url(#brush-shadow)\"":"",data=Base64.getEncoder().encodeToString(bytes);double spacing=Double.isFinite(o.letterSpacing)?Math.max(0,o.letterSpacing):Math.max(.75,fs*.06),reveal=clamp(o.revealProgress,0,1);
    return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\""+fmt(width)+"\" height=\""+fmt(height)+"\" viewBox=\"0 0 "+fmt(width)+" "+fmt(height)+"\"><image width=\""+fmt(width)+"\" height=\""+fmt(height)+"\" preserveAspectRatio=\"xMidYMid slice\" href=\"data:"+mime+";base64,"+data+"\"/><defs><path id=\"brush-path\" d=\""+esc(path.d)+"\"/>"+gradient+shadow+"<mask id=\"brush-reveal\"><rect width=\"100%\" height=\"100%\" fill=\"black\"/><path d=\""+esc(path.d)+"\" pathLength=\"1\" fill=\"none\" stroke=\"white\" stroke-width=\""+fmt(fs*2.4)+"\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-dasharray=\"1\" stroke-dashoffset=\""+fmt(1-reveal)+"\"/></mask></defs><g mask=\"url(#brush-reveal)\" opacity=\""+fmt(clamp(o.opacity,0,1))+"\""+filter+"><text font-family=\""+esc(o.fontFamily)+"\" font-size=\""+fmt(fs)+"\" font-weight=\""+esc(o.fontWeight)+"\" letter-spacing=\""+fmt(spacing)+"\" fill=\""+fill+"\" stroke=\""+esc(o.strokeColor)+"\" stroke-width=\""+fmt(Math.max(0,o.strokeWidth))+"\" paint-order=\"stroke fill\"><textPath href=\"#brush-path\" xlink:href=\"#brush-path\" startOffset=\"0\" spacing=\"exact\">"+esc(repeat)+"</textPath></text></g></svg>\n";
  }
}
