brush_point <- function(x,y) c(x=as.numeric(x),y=as.numeric(y))
.finite <- function(p) length(p)>=2 && all(is.finite(p)); .clamp <- function(v,a,b) if(is.finite(v)) min(b,max(a,v)) else a; .dist <- function(a,b) sqrt(sum((b-a)^2))
.fmt <- function(v){v<-round(v,2);if(v==0)return("0");sub("\\.?0+$","",sprintf("%0.2f",v))};.fp<-function(p)paste(.fmt(p[1]),.fmt(p[2]));.along<-function(a,b,d){l<-.dist(a,b);if(l==0)return(a);t<-min(1,d/l);a+(b-a)*t};.turn<-function(a,b,c){u<-b-a;v<-c-b;ul<-sqrt(sum(u*u));vl<-sqrt(sum(v*v));if(ul==0||vl==0)return(0);acos(.clamp(sum(u*v)/(ul*vl),-1,1))*180/pi}
build_rounded_drawing_path<-function(input,font_size=40){p<-Filter(.finite,input);if(!length(p))return("");if(length(p)==1)return(paste("M",.fp(p[[1]])));out<-paste("M",.fp(p[[1]]));radius<-max(12,font_size*1.25);if(length(p)>2)for(i in 2:(length(p)-1)){d<-min(radius,.dist(p[[i-1]],p[[i]])*0.45,.dist(p[[i]],p[[i+1]])*0.45);out<-c(out,paste("L",.fp(.along(p[[i]],p[[i-1]],d)),"Q",.fp(p[[i]]),.fp(.along(p[[i]],p[[i+1]],d))))};paste(c(out,paste("L",.fp(p[[length(p)]]))),collapse=" ")}
create_drawing_path<-function(p,font_size=40)if(.finite(p))list(points=list(p),d=paste("M",.fp(p)),font_size=font_size)else list(points=list(),d="",font_size=font_size)
append_drawing_point<-function(path,p){n<-path$points;if(!.finite(p)||!length(n)||.dist(n[[length(n)]],p)<3)return(path);if(length(n)==1||.turn(n[[length(n)-1]],n[[length(n)]],p)>=18)n[[length(n)+1]]<-p else n[[length(n)]]<-p;list(points=n,d=build_rounded_drawing_path(n,path$font_size),font_size=path$font_size)}
.drawing<-function(points,fs){path<-NULL;for(p in points)if(.finite(p))path<-if(is.null(path))create_drawing_path(p,fs)else append_drawing_point(path,p);if(!is.null(path)&&length(path$points)>=2)path else NULL}
.perp<-function(p,a,b){d<-b-a;l<-sum(d*d);if(l==0)return(.dist(p,a));t<-.clamp(sum((p-a)*d)/l,0,1);.dist(p,a+t*d)}
.simplify<-function(p,tol){if(length(p)<=2)return(p);keep<-rep(FALSE,length(p));keep[c(1,length(p))]<-TRUE;stack<-list(c(1,length(p)));while(length(stack)){r<-stack[[length(stack)]];stack<-stack[-length(stack)];best<-0;index<-NA;if(r[2]>r[1]+1)for(i in (r[1]+1):(r[2]-1)){d<-.perp(p[[i]],p[[r[1]]],p[[r[2]]]);if(d>best){best<-d;index<-i}};if(!is.na(index)&&best>tol){keep[index]<-TRUE;stack<-c(stack,list(c(r[1],index),c(index,r[2])))}};p[keep]}
prepare_arc_length_path<-function(input,minimum=0.5){valid<-Filter(.finite,input);filtered<-list();for(p in valid)if(!length(filtered)||.dist(filtered[[length(filtered)]],p)>=minimum)filtered[[length(filtered)+1]]<-p;if(length(valid)&&length(filtered)&&.dist(filtered[[length(filtered)]],valid[[length(valid)]])>0)filtered[[length(filtered)+1]]<-valid[[length(valid)]];p<-.simplify(filtered,max(minimum*0.5,0.1));segments<-list();total<-0;if(length(p)>1)for(i in 2:length(p)){l<-.dist(p[[i-1]],p[[i]]);if(l>0){segments[[length(segments)+1]]<-list(a=p[[i-1]],b=p[[i]],start=total,length=l);total<-total+l}};list(points=p,segments=segments,total_length=total)}
.point_at<-function(path,d){if(!length(path$segments))return(brush_point(0,0));d<-.clamp(d,0,path$total_length);for(s in path$segments)if(d<=s$start+s$length){t<-.clamp((d-s$start)/s$length,0,1);return(s$a+(s$b-s$a)*t)};path$segments[[length(path$segments)]]$b}
sample_at<-function(path,progress,font_size=40){progress<-.clamp(progress,0,1);if(path$total_length<=0)return(list(x=0,y=0,angle=0,progress=progress));d<-path$total_length*progress;w<-max(min(max(font_size*1.1,0.75),path$total_length*0.06),0.75);a<-.point_at(path,d-w);b<-.point_at(path,d+w);p<-.point_at(path,d);list(x=p[1],y=p[2],angle=atan2(b[2]-a[2],b[1]-a[1]),progress=progress)}
stable_repeated_text<-function(text,font_size){p<-trimws(text);if(!nchar(p))return("");count<-min(256,max(16,ceiling(20000/max(font_size,nchar(p,type="chars")*font_size*0.62))));paste(rep(p,count),collapse="   ")}
.esc<-function(s){s<-gsub("&","&amp;",s,fixed=TRUE);s<-gsub("<","&lt;",s,fixed=TRUE);s<-gsub(">","&gt;",s,fixed=TRUE);s<-gsub('"',"&quot;",s,fixed=TRUE);gsub("'","&apos;",s,fixed=TRUE)}
.base64<-function(bytes){a<-strsplit("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/","")[[1]];v<-as.integer(bytes);if(!length(v))return("");padding<-(3-length(v)%%3)%%3;if(padding)v<-c(v,rep.int(0L,padding));triples<-matrix(v,nrow=3);n<-triples[1,]*65536+triples[2,]*256+triples[3,];out<-rbind(a[floor(n/262144)%%64+1],a[floor(n/4096)%%64+1],a[floor(n/64)%%64+1],a[n%%64+1]);if(padding>=2)out[3,ncol(out)]<-"=";if(padding>=1)out[4,ncol(out)]<-"=";paste0(out,collapse="")}
render_svg<-function(image_bytes,mime,width,height,points,text,options=list()){if(!mime%in%c("image/png","image/jpeg","image/webp","image/gif","image/avif"))stop("unsupported MIME");defaults<-list(font_size=40,font_family="Arial, sans-serif",font_weight="700",letter_spacing=NULL,color="#ffffff",magic_gradient=FALSE,opacity=1,stroke_color="rgba(15,23,42,0.72)",stroke_width=1.5,shadow=TRUE,repeat_text=TRUE,reveal_progress=1);o<-modifyList(defaults,options);phrase<-trimws(text);path<-.drawing(points,o$font_size);if(!nchar(phrase)||is.null(path))stop("text and two points required");repeated<-if(o$repeat_text)stable_repeated_text(phrase,o$font_size)else phrase;gradient<-if(o$magic_gradient)'<linearGradient id="brush-gradient" x1="100" y1="150" x2="900" y2="850" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#ec4899"/><stop offset="20%" stop-color="#f97316"/><stop offset="40%" stop-color="#facc15"/><stop offset="60%" stop-color="#10b981"/><stop offset="80%" stop-color="#3b82f6"/><stop offset="100%" stop-color="#8b5cf6"/></linearGradient>'else"";shadow<-if(o$shadow)'<filter id="brush-shadow"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#0f172a" flood-opacity="0.65"/></filter>'else"";filter<-if(o$shadow)' filter="url(#brush-shadow)"'else"";fill<-if(o$magic_gradient)"url(#brush-gradient)"else .esc(o$color);spacing<-if(is.null(o$letter_spacing))max(0.75,o$font_size*0.06)else o$letter_spacing;reveal<-.clamp(o$reveal_progress,0,1);d<-.esc(path$d);paste0('<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="',.fmt(width),'" height="',.fmt(height),'" viewBox="0 0 ',.fmt(width),' ',.fmt(height),'"><image width="',.fmt(width),'" height="',.fmt(height),'" preserveAspectRatio="xMidYMid slice" href="data:',mime,';base64,',.base64(image_bytes),'"/><defs><path id="brush-path" d="',d,'"/>',gradient,shadow,'<mask id="brush-reveal"><rect width="100%" height="100%" fill="black"/><path d="',d,'" pathLength="1" fill="none" stroke="white" stroke-width="',.fmt(o$font_size*2.4),'" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="1" stroke-dashoffset="',.fmt(1-reveal),'"/></mask></defs><g mask="url(#brush-reveal)" opacity="',.fmt(.clamp(o$opacity,0,1)),'"',filter,'><text font-family="',.esc(o$font_family),'" font-size="',.fmt(o$font_size),'" font-weight="',.esc(o$font_weight),'" letter-spacing="',.fmt(spacing),'" fill="',fill,'" stroke="',.esc(o$stroke_color),'" stroke-width="',.fmt(max(0,o$stroke_width)),'" paint-order="stroke fill"><textPath href="#brush-path" xlink:href="#brush-path" startOffset="0" spacing="exact">',.esc(repeated),'</textPath></text></g></svg>\n')}
