export const MIN_DRAWING_POINT_DISTANCE = 3;
export const STRAIGHT_DIRECTION_TOLERANCE_DEGREES = 18;
const finite = p => p && Number.isFinite(p.x) && Number.isFinite(p.y);
const clamp = (v, a, b) => Number.isFinite(v) ? Math.min(b, Math.max(a, v)) : a;
const distance = (a, b) => Math.hypot(b.x - a.x, b.y - a.y);
const fmt = v => { const n = Number(v.toFixed(2)); return Object.is(n, -0) ? "0" : String(n); };
const fp = p => `${fmt(p.x)} ${fmt(p.y)}`;
const along = (a, b, d) => { const l = distance(a, b); if (!l) return a; const t = Math.min(1, d / l); return { x: a.x + (b.x-a.x)*t, y: a.y+(b.y-a.y)*t }; };
const turn = (a,b,c) => { const ux=b.x-a.x, uy=b.y-a.y, vx=c.x-b.x, vy=c.y-b.y, ul=Math.hypot(ux,uy), vl=Math.hypot(vx,vy); return !ul||!vl ? 0 : Math.acos(clamp((ux*vx+uy*vy)/(ul*vl),-1,1))*180/Math.PI; };

export function buildRoundedDrawingPath(input, fontSize=40) {
  const points=input.filter(finite); if (!points.length) return ""; if(points.length===1) return `M ${fp(points[0])}`;
  const out=[`M ${fp(points[0])}`], radius=Math.max(12,fontSize*1.25);
  for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1],d=Math.min(radius,distance(a,b)*.45,distance(b,c)*.45);out.push(`L ${fp(along(b,a,d))} Q ${fp(b)} ${fp(along(b,c,d))}`);}
  out.push(`L ${fp(points.at(-1))}`); return out.join(" ");
}
export function createDrawingPath(point,fontSize=40){return finite(point)?{points:[point],d:`M ${fp(point)}`,fontSize}:{points:[],d:"",fontSize};}
export function appendDrawingPoint(path,point){if(!finite(point))return path;const p=path.points,last=p.at(-1);if(!last||distance(last,point)<3)return path;const next=p.length===1?[...p,point]:turn(p.at(-2),last,point)<18?[...p.slice(0,-1),point]:[...p,point];return{points:next,d:buildRoundedDrawingPath(next,path.fontSize),fontSize:path.fontSize};}
export const finishDrawingPath=path=>path.points.length>=2?path:null;
export function drawingPathFromPoints(points,fontSize=40){const valid=points.filter(finite);if(!valid.length)return null;let path=createDrawingPath(valid[0],fontSize);for(const p of valid.slice(1))path=appendDrawingPoint(path,p);return finishDrawingPath(path);}
const perpendicular=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return distance(p,a);const t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return distance(p,{x:a.x+t*dx,y:a.y+t*dy});};
function simplify(points,tolerance){if(points.length<=2)return points;const keep=Array(points.length).fill(false);keep[0]=keep.at(-1)=true;const stack=[[0,points.length-1]];while(stack.length){const[first,last]=stack.pop();let best=0,index=-1;for(let i=first+1;i<last;i++){const d=perpendicular(points[i],points[first],points[last]);if(d>best){best=d;index=i;}}if(best>tolerance){keep[index]=true;stack.push([first,index],[index,last]);}}return points.filter((_,i)=>keep[i]);}
export function prepareArcLengthPath(input,minimum=.5){minimum=Number.isFinite(minimum)?Math.max(0,minimum):.5;const valid=input.filter(finite),filtered=[];for(const p of valid)if(!filtered.length||distance(filtered.at(-1),p)>=minimum)filtered.push(p);if(valid.length&&filtered.length&&distance(filtered.at(-1),valid.at(-1))>0)filtered.push(valid.at(-1));const points=simplify(filtered,Math.max(minimum*.5,.1)),segments=[];let totalLength=0;for(let i=1;i<points.length;i++){const length=distance(points[i-1],points[i]);if(length>0){segments.push({start:points[i-1],end:points[i],startDistance:totalLength,length});totalLength+=length;}}return{points,segments,totalLength};}
function pointAt(path,d){if(!path.segments.length)return{x:0,y:0};d=clamp(d,0,path.totalLength);if(d<=0)return path.segments[0].start;if(d>=path.totalLength)return path.segments.at(-1).end;let lo=0,hi=path.segments.length-1;while(lo<hi){const m=(lo+hi)>>1,s=path.segments[m];if(d>s.startDistance+s.length)lo=m+1;else hi=m;}const s=path.segments[lo],t=clamp((d-s.startDistance)/s.length,0,1);return{x:s.start.x+(s.end.x-s.start.x)*t,y:s.start.y+(s.end.y-s.start.y)*t};}
export function sampleAt(path,progress,fontSize=40){progress=clamp(progress,0,1);if(!path.totalLength)return{x:0,y:0,angle:0,progress};const d=path.totalLength*progress,w=Math.max(Math.min(Math.max(fontSize*1.1,.75),path.totalLength*.06),.75),a=pointAt(path,d-w),b=pointAt(path,d+w);return{...pointAt(path,d),angle:Math.atan2(b.y-a.y,b.x-a.x),progress};}
export function getStableRepeatedText(text,fontSize){const phrase=text.trim();if(!phrase)return"";const width=Math.max(fontSize,[...phrase].length*fontSize*.62),count=Math.min(256,Math.max(16,Math.ceil(20000/width)));return Array(count).fill(phrase).join("   ");}
const esc=s=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
export function renderSvg(bytes,mime,width,height,points,text,o={}){if(!["image/png","image/jpeg","image/webp","image/gif","image/avif"].includes(mime))throw Error("Unsupported image MIME type");if(!(width>0&&height>0&&Number.isFinite(width+height)))throw Error("Invalid dimensions");const phrase=text.trim(),fs=Number.isFinite(o.fontSize)&&o.fontSize>0?o.fontSize:40,path=drawingPathFromPoints(points,fs);if(!phrase||!path)throw Error("Text and two points are required");const repeat=o.repeatText===false?phrase:getStableRepeatedText(phrase,fs),magic=!!o.magicGradient,reveal=clamp(o.revealProgress??1,0,1),opacity=clamp(o.opacity??1,0,1),spacing=Number.isFinite(o.letterSpacing)?Math.max(0,o.letterSpacing):Math.max(.75,fs*.06),shadow=o.shadow===false?"":'<filter id="brush-shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#0f172a" flood-opacity="0.65"/></filter>',gradient=magic?'<linearGradient id="brush-gradient" x1="100" y1="150" x2="900" y2="850" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#ec4899"/><stop offset="20%" stop-color="#f97316"/><stop offset="40%" stop-color="#facc15"/><stop offset="60%" stop-color="#10b981"/><stop offset="80%" stop-color="#3b82f6"/><stop offset="100%" stop-color="#8b5cf6"/></linearGradient>':"",fill=magic?"url(#brush-gradient)":esc(o.color??"#fff"),filter=o.shadow===false?"":' filter="url(#brush-shadow)"';
return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${fmt(width)}" height="${fmt(height)}" viewBox="0 0 ${fmt(width)} ${fmt(height)}"><image width="${fmt(width)}" height="${fmt(height)}" preserveAspectRatio="xMidYMid slice" href="data:${mime};base64,${Buffer.from(bytes).toString("base64")}"/><defs><path id="brush-path" d="${esc(path.d)}"/>${gradient}${shadow}<mask id="brush-reveal" x="0" y="0" width="${fmt(width)}" height="${fmt(height)}" maskUnits="userSpaceOnUse"><rect width="100%" height="100%" fill="black"/><path d="${esc(path.d)}" pathLength="1" fill="none" stroke="white" stroke-width="${fmt(fs*2.4)}" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="1" stroke-dashoffset="${fmt(1-reveal)}"/></mask></defs><g mask="url(#brush-reveal)" opacity="${fmt(opacity)}"${filter}><text font-family="${esc(o.fontFamily??"Arial, sans-serif")}" font-size="${fmt(fs)}" font-weight="${esc(o.fontWeight??700)}" letter-spacing="${fmt(spacing)}" fill="${fill}" stroke="${esc(o.strokeColor??"rgba(15,23,42,0.72)")}" stroke-width="${fmt(Math.max(0,o.strokeWidth??1.5))}" paint-order="stroke fill"><textPath href="#brush-path" xlink:href="#brush-path" startOffset="0" spacing="exact">${esc(repeat)}</textPath></text></g></svg>\n`;}
