require "base64"
module Brush
 Point=Struct.new(:x,:y,keyword_init:true);DrawingPath=Struct.new(:points,:d,:font_size,keyword_init:true);ArcPath=Struct.new(:points,:segments,:total_length,keyword_init:true);PathSample=Struct.new(:x,:y,:angle,:progress,keyword_init:true)
 DEFAULTS={font_size:40,font_family:"Arial, sans-serif",font_weight:"700",letter_spacing:nil,color:"#ffffff",magic_gradient:false,opacity:1,stroke_color:"rgba(15,23,42,0.72)",stroke_width:1.5,shadow:true,repeat_text:true,reveal_progress:1}.freeze
 module_function
 def finite?(p)=p&&p.x.finite?&&p.y.finite?;def clamp(v,a,b)=v.finite? ? [[v,a].max,b].min : a;def distance(a,b)=Math.hypot(b.x-a.x,b.y-a.y)
 def fmt(v);n=v.round(2);n.zero? ? "0" : format("%.2f",n).sub(/\.?0+$/,'')end;def fp(p)="#{fmt(p.x)} #{fmt(p.y)}";def along(a,b,d);l=distance(a,b);return a if l.zero?;t=[1,d/l].min;Point.new(x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t)end
 def turn(a,b,c);ux=b.x-a.x;uy=b.y-a.y;vx=c.x-b.x;vy=c.y-b.y;ul=Math.hypot(ux,uy);vl=Math.hypot(vx,vy);return 0 if ul.zero?||vl.zero?;Math.acos(clamp((ux*vx+uy*vy)/(ul*vl),-1,1))*180/Math::PI end
 def build_rounded_drawing_path(input,font_size=40);p=input.select{|v|finite?(v)};return""if p.empty?;return"M #{fp(p[0])}"if p.length==1;out=["M #{fp(p[0])}"];radius=[12,font_size*1.25].max;(1...p.length-1).each{|i|d=[radius,distance(p[i-1],p[i])*0.45,distance(p[i],p[i+1])*0.45].min;out<<"L #{fp(along(p[i],p[i-1],d))} Q #{fp(p[i])} #{fp(along(p[i],p[i+1],d))}"};out<<"L #{fp(p[-1])}";out.join(" ")end
 def create_drawing_path(p,fs=40)=finite?(p) ? DrawingPath.new(points:[p],d:"M #{fp(p)}",font_size:fs) : DrawingPath.new(points:[],d:"",font_size:fs)
 def append_drawing_point(path,p);return path unless finite?(p)&&path.points.any?&&distance(path.points[-1],p)>=3;n=path.points.dup;if n.length==1||turn(n[-2],n[-1],p)>=18 then n<<p else n[-1]=p end;DrawingPath.new(points:n,d:build_rounded_drawing_path(n,path.font_size),font_size:path.font_size)end
 def drawing_path_from_points(points,fs=40);path=nil;points.each{|p|path=path ? append_drawing_point(path,p):create_drawing_path(p,fs)if finite?(p)};path if path&&path.points.length>=2 end
 def perp(p,a,b);dx=b.x-a.x;dy=b.y-a.y;l=dx*dx+dy*dy;return distance(p,a)if l.zero?;t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);distance(p,Point.new(x:a.x+t*dx,y:a.y+t*dy))end
 def simplify(p,tol);return p if p.length<=2;keep=Array.new(p.length,false);keep[0]=keep[-1]=true;stack=[[0,p.length-1]];until stack.empty?;first,last=stack.pop;best=0;index=nil;(first+1...last).each{|i|d=perp(p[i],p[first],p[last]);best,index=d,i if d>best};if best>tol;keep[index]=true;stack<<[first,index]<<[index,last]end;end;p.each_index.filter_map{|i|p[i]if keep[i]}end
 def prepare_arc_length_path(input,minimum=0.5);minimum=minimum.finite? ? [0,minimum].max : 0.5;valid=input.select{|p|finite?(p)};filtered=[];valid.each{|p|filtered<<p if filtered.empty?||distance(filtered[-1],p)>=minimum};filtered<<valid[-1]if valid.any?&&filtered.any?&&distance(filtered[-1],valid[-1])>0;p=simplify(filtered,[minimum*0.5,0.1].max);segments=[];total=0.0;p.each_cons(2){|a,b|l=distance(a,b);if l>0;segments<<[a,b,total,l];total+=l end};ArcPath.new(points:p,segments:segments,total_length:total)end
 def point_at(path,d);return Point.new(x:0,y:0)if path.segments.empty?;d=clamp(d,0,path.total_length);path.segments.each{|a,b,start,length|if d<=start+length;t=clamp((d-start)/length,0,1);return Point.new(x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t)end};path.segments[-1][1]end
 def sample_at(path,progress,fs=40);progress=clamp(progress,0,1);return PathSample.new(x:0,y:0,angle:0,progress:progress)if path.total_length<=0;d=path.total_length*progress;w=[[[fs*1.1,0.75].max,path.total_length*0.06].min,0.75].max;a=point_at(path,d-w);b=point_at(path,d+w);p=point_at(path,d);PathSample.new(x:p.x,y:p.y,angle:Math.atan2(b.y-a.y,b.x-a.x),progress:progress)end
 def stable_repeated_text(text,fs);phrase=text.strip;return""if phrase.empty?;count=(20_000/[fs,phrase.length*fs*0.62].max).ceil.clamp(16,256);Array.new(count,phrase).join("   ")end
 def esc(v)=v.to_s.gsub('&','&amp;').gsub('<','&lt;').gsub('>','&gt;').gsub('"','&quot;').gsub("'",'&apos;')
 def render_svg(bytes,mime,width,height,points,text,options={});raise ArgumentError,"unsupported MIME"unless%w[image/png image/jpeg image/webp image/gif image/avif].include?(mime);raise ArgumentError,"invalid dimensions"unless width.finite?&&height.finite?&&width>0&&height>0;o=DEFAULTS.merge(options);phrase=text.strip;fs=o[:font_size].finite?&&o[:font_size]>0 ? o[:font_size] : 40;path=drawing_path_from_points(points,fs);raise ArgumentError,"text and two points required"if phrase.empty?||!path;repeat=o[:repeat_text] ? stable_repeated_text(phrase,fs) : phrase;gradient=o[:magic_gradient] ? '<linearGradient id="brush-gradient" x1="100" y1="150" x2="900" y2="850" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#ec4899"/><stop offset="20%" stop-color="#f97316"/><stop offset="40%" stop-color="#facc15"/><stop offset="60%" stop-color="#10b981"/><stop offset="80%" stop-color="#3b82f6"/><stop offset="100%" stop-color="#8b5cf6"/></linearGradient>' : '';shadow=o[:shadow] ? '<filter id="brush-shadow"><feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#0f172a" flood-opacity="0.65"/></filter>' : '';fill=o[:magic_gradient] ? 'url(#brush-gradient)' : esc(o[:color]);filter=o[:shadow] ? ' filter="url(#brush-shadow)"' : '';spacing=o[:letter_spacing]||[0.75,fs*0.06].max;reveal=clamp(o[:reveal_progress],0,1)
 %(<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="#{fmt(width)}" height="#{fmt(height)}" viewBox="0 0 #{fmt(width)} #{fmt(height)}"><image width="#{fmt(width)}" height="#{fmt(height)}" preserveAspectRatio="xMidYMid slice" href="data:#{mime};base64,#{Base64.strict_encode64(bytes)}"/><defs><path id="brush-path" d="#{esc(path.d)}"/>#{gradient}#{shadow}<mask id="brush-reveal"><rect width="100%" height="100%" fill="black"/><path d="#{esc(path.d)}" pathLength="1" fill="none" stroke="white" stroke-width="#{fmt(fs*2.4)}" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="1" stroke-dashoffset="#{fmt(1-reveal)}"/></mask></defs><g mask="url(#brush-reveal)" opacity="#{fmt(clamp(o[:opacity],0,1))}"#{filter}><text font-family="#{esc(o[:font_family])}" font-size="#{fmt(fs)}" font-weight="#{esc(o[:font_weight])}" letter-spacing="#{fmt(spacing)}" fill="#{fill}" stroke="#{esc(o[:stroke_color])}" stroke-width="#{fmt([0,o[:stroke_width]].max)}" paint-order="stroke fill"><textPath href="#brush-path" xlink:href="#brush-path" startOffset="0" spacing="exact">#{esc(repeat)}</textPath></text></g></svg>\n)
 end
end
