#pragma once
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace brush {
struct Point{double x,y;};struct DrawingPath{std::vector<Point>points;std::string d;double fontSize=40;};struct Segment{Point a,b;double start,length;};struct ArcPath{std::vector<Point>points;std::vector<Segment>segments;double totalLength=0;};struct PathSample{double x,y,angle,progress;};
struct Options{double fontSize=40,letterSpacing=NAN,opacity=1,strokeWidth=1.5,revealProgress=1;std::string fontFamily="Arial, sans-serif",fontWeight="700",color="#ffffff",strokeColor="rgba(15,23,42,0.72)";bool magicGradient=false,shadow=true,repeatText=true;};
inline bool finite(Point p){return std::isfinite(p.x)&&std::isfinite(p.y);}inline double clamp(double v,double a,double b){return std::isfinite(v)?std::min(b,std::max(a,v)):a;}inline double distance(Point a,Point b){return std::hypot(b.x-a.x,b.y-a.y);}inline std::string format(double v){v=std::round(v*100)/100;if(v==0)return"0";std::ostringstream s;s<<std::fixed<<std::setprecision(2)<<v;auto r=s.str();while(!r.empty()&&r.back()=='0')r.pop_back();if(!r.empty()&&r.back()=='.')r.pop_back();return r;}inline std::string fp(Point p){return format(p.x)+" "+format(p.y);}inline Point along(Point a,Point b,double d){auto l=distance(a,b);if(!l)return a;auto t=std::min(1.0,d/l);return{a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t};}inline double turn(Point a,Point b,Point c){auto ux=b.x-a.x,uy=b.y-a.y,vx=c.x-b.x,vy=c.y-b.y,ul=std::hypot(ux,uy),vl=std::hypot(vx,vy);return !ul||!vl?0:std::acos(clamp((ux*vx+uy*vy)/(ul*vl),-1,1))*180/M_PI;}
inline std::string buildRoundedDrawingPath(const std::vector<Point>&input,double fs=40){std::vector<Point>p;for(auto v:input)if(finite(v))p.push_back(v);if(p.empty())return{};if(p.size()==1)return"M "+fp(p[0]);std::string out="M "+fp(p[0]);auto radius=std::max(12.0,fs*1.25);for(size_t i=1;i+1<p.size();++i){auto d=std::min({radius,distance(p[i-1],p[i])*.45,distance(p[i],p[i+1])*.45});out+=" L "+fp(along(p[i],p[i-1],d))+" Q "+fp(p[i])+" "+fp(along(p[i],p[i+1],d));}return out+" L "+fp(p.back());}
inline DrawingPath createDrawingPath(Point p,double fs=40){return finite(p)?DrawingPath{{p},"M "+fp(p),fs}:DrawingPath{{},"",fs};}inline DrawingPath appendDrawingPoint(const DrawingPath&path,Point point){if(!finite(point)||path.points.empty()||distance(path.points.back(),point)<3)return path;auto p=path.points;if(p.size()==1||turn(p[p.size()-2],p.back(),point)>=18)p.push_back(point);else p.back()=point;return{p,buildRoundedDrawingPath(p,path.fontSize),path.fontSize};}inline DrawingPath drawingPathFromPoints(const std::vector<Point>&points,double fs=40){DrawingPath path;bool started=false;for(auto p:points)if(finite(p)){if(!started){path=createDrawingPath(p,fs);started=true;}else path=appendDrawingPoint(path,p);}return path.points.size()>=2?path:DrawingPath{};}
inline double perp(Point p,Point a,Point b){auto dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return distance(p,a);auto t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return distance(p,{a.x+t*dx,a.y+t*dy});}inline std::vector<Point> simplify(const std::vector<Point>&p,double tolerance){if(p.size()<=2)return p;std::vector<bool>keep(p.size());keep.front()=keep.back()=true;std::vector<std::pair<size_t,size_t>>stack{{0,p.size()-1}};while(!stack.empty()){auto[first,last]=stack.back();stack.pop_back();double best=0;size_t index=0;for(auto i=first+1;i<last;i++){auto d=perp(p[i],p[first],p[last]);if(d>best){best=d;index=i;}}if(best>tolerance){keep[index]=true;stack.push_back({first,index});stack.push_back({index,last});}}std::vector<Point>r;for(size_t i=0;i<p.size();i++)if(keep[i])r.push_back(p[i]);return r;}
inline ArcPath prepareArcLengthPath(const std::vector<Point>&input,double minimum=.5){minimum=std::isfinite(minimum)?std::max(0.0,minimum):.5;std::vector<Point>valid,filtered;for(auto p:input)if(finite(p))valid.push_back(p);for(auto p:valid)if(filtered.empty()||distance(filtered.back(),p)>=minimum)filtered.push_back(p);if(!valid.empty()&&!filtered.empty()&&distance(filtered.back(),valid.back())>0)filtered.push_back(valid.back());ArcPath path;path.points=simplify(filtered,std::max(minimum*.5,.1));for(size_t i=1;i<path.points.size();i++){auto l=distance(path.points[i-1],path.points[i]);if(l>0){path.segments.push_back({path.points[i-1],path.points[i],path.totalLength,l});path.totalLength+=l;}}return path;}inline Point pointAt(const ArcPath&p,double d){if(p.segments.empty())return{0,0};d=clamp(d,0,p.totalLength);for(auto&s:p.segments)if(d<=s.start+s.length){auto t=clamp((d-s.start)/s.length,0,1);return{s.a.x+(s.b.x-s.a.x)*t,s.a.y+(s.b.y-s.a.y)*t};}return p.segments.back().b;}inline PathSample sampleAt(const ArcPath&p,double progress,double fs=40){progress=clamp(progress,0,1);if(p.totalLength<=0)return{0,0,0,progress};double d=p.totalLength*progress,w=std::max(std::min(std::max(fs*1.1,.75),p.totalLength*.06),.75);Point a=pointAt(p,d-w),b=pointAt(p,d+w),v=pointAt(p,d);return{v.x,v.y,std::atan2(b.y-a.y,b.x-a.x),progress};}
inline std::string stableRepeatedText(std::string text,double fs){auto first=text.find_first_not_of(" \t\r\n"),last=text.find_last_not_of(" \t\r\n");if(first==std::string::npos)return{};auto phrase=text.substr(first,last-first+1);auto count=std::min(256,std::max(16,(int)std::ceil(20000/std::max(fs,phrase.size()*fs*.62))));std::string out;for(int i=0;i<count;i++){if(i)out+="   ";out+=phrase;}return out;}inline std::string esc(std::string s){struct R{std::string a,b;};for(auto r:{R{"&","&amp;"},R{"<","&lt;"},R{">","&gt;"},R{"\"","&quot;"},R{"'","&apos;"}}){size_t p=0;while((p=s.find(r.a,p))!=std::string::npos){s.replace(p,r.a.size(),r.b);p+=r.b.size();}}return s;}inline std::string base64(const std::vector<std::uint8_t>&data){static constexpr char A[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";std::string r;for(size_t i=0;i<data.size();i+=3){unsigned a=data[i],b=i+1<data.size()?data[i+1]:0,c=i+2<data.size()?data[i+2]:0,n=(a<<16)|(b<<8)|c;r+=A[(n>>18)&63];r+=A[(n>>12)&63];r+=i+1<data.size()?A[(n>>6)&63]:'=';r+=i+2<data.size()?A[n&63]:'=';}return r;}
inline std::string renderSvg(const std::vector<std::uint8_t>&bytes,const std::string&mime,double width,double height,const std::vector<Point>&points,const std::string&text,Options o={}){if(mime!="image/png"&&mime!="image/jpeg"&&mime!="image/webp"&&mime!="image/gif"&&mime!="image/avif")throw std::invalid_argument("unsupported MIME");if(!(std::isfinite(width+height)&&width>0&&height>0))throw std::invalid_argument("invalid dimensions");double fs=std::isfinite(o.fontSize)&&o.fontSize>0?o.fontSize:40;DrawingPath path=drawingPathFromPoints(points,fs);auto phrase=text;phrase.erase(0,phrase.find_first_not_of(" \t\r\n"));if(phrase.empty()||path.points.size()<2)throw std::invalid_argument("text and two points required");std::string repeated=o.repeatText?stableRepeatedText(phrase,fs):phrase,gradient=o.magicGradient?"<linearGradient id=\"brush-gradient\" x1=\"100\" y1=\"150\" x2=\"900\" y2=\"850\" gradientUnits=\"userSpaceOnUse\"><stop offset=\"0%\" stop-color=\"#ec4899\"/><stop offset=\"20%\" stop-color=\"#f97316\"/><stop offset=\"40%\" stop-color=\"#facc15\"/><stop offset=\"60%\" stop-color=\"#10b981\"/><stop offset=\"80%\" stop-color=\"#3b82f6\"/><stop offset=\"100%\" stop-color=\"#8b5cf6\"/></linearGradient>":"",shadow=o.shadow?"<filter id=\"brush-shadow\"><feDropShadow dx=\"0\" dy=\"2\" stdDeviation=\"2\" flood-color=\"#0f172a\" flood-opacity=\"0.65\"/></filter>":"",fill=o.magicGradient?"url(#brush-gradient)":esc(o.color),filter=o.shadow?" filter=\"url(#brush-shadow)\"":"";double spacing=std::isfinite(o.letterSpacing)?std::max(0.0,o.letterSpacing):std::max(.75,fs*.06),reveal=clamp(o.revealProgress,0,1);
return"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\""+format(width)+"\" height=\""+format(height)+"\" viewBox=\"0 0 "+format(width)+" "+format(height)+"\"><image width=\""+format(width)+"\" height=\""+format(height)+"\" preserveAspectRatio=\"xMidYMid slice\" href=\"data:"+mime+";base64,"+base64(bytes)+"\"/><defs><path id=\"brush-path\" d=\""+esc(path.d)+"\"/>"+gradient+shadow+"<mask id=\"brush-reveal\"><rect width=\"100%\" height=\"100%\" fill=\"black\"/><path d=\""+esc(path.d)+"\" pathLength=\"1\" fill=\"none\" stroke=\"white\" stroke-width=\""+format(fs*2.4)+"\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-dasharray=\"1\" stroke-dashoffset=\""+format(1-reveal)+"\"/></mask></defs><g mask=\"url(#brush-reveal)\" opacity=\""+format(clamp(o.opacity,0,1))+"\""+filter+"><text font-family=\""+esc(o.fontFamily)+"\" font-size=\""+format(fs)+"\" font-weight=\""+esc(o.fontWeight)+"\" letter-spacing=\""+format(spacing)+"\" fill=\""+fill+"\" stroke=\""+esc(o.strokeColor)+"\" stroke-width=\""+format(std::max(0.0,o.strokeWidth))+"\" paint-order=\"stroke fill\"><textPath href=\"#brush-path\" xlink:href=\"#brush-path\" startOffset=\"0\" spacing=\"exact\">"+esc(repeated)+"</textPath></text></g></svg>\n";}
}
